package com.achobeta.common.base;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * <span>
 * The primary keys of classes that inherit this entity are
 * Long type ids generated by the snowflake algorithm.
 * </span>
 *
 * @author jettcc in 2023/12/07
 * @version 1.0
 */
@Getter
@Setter
public class BaseAssignIDEntity extends BaseEntity implements Serializable {
    /**
     * id, incr
     */
    @TableId(type = IdType.ASSIGN_ID, value = "id")
    private Long id;

}
