spring:
  config:
    name: achobeta-recruitment
  profiles:
    active: @profiles.active@
# 日志配置
logging:
  level:
    com.achobeta: @logging.level@
    org.springframework: warn
    tech.powerjob.worker.background: warn
  config: classpath:logback-plus.xml

# mp设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml文件地址,默认值
  configuration:
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1 #逻辑已删除值(默认为1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为0)
      id-type: ASSIGN_ID #id为雪花算法生成 设置为none->为遵循版本默认，可见这个版本默认为assign_id
      update-strategy: not_null #更新策略:只更新非空字段
      insert-strategy: not_null #插入策略:为空走默认值
  db-type: MYSQL # 分页时指定数据库类型

resource:
  code:
    workerId: 1
  upload:
    maxFileSize: 20
    maxRequestSize: 100

