spring:
  config:
    name: achobeta-recruitment
  profiles:
    active: @profiles.active@

# 日志配置
logging:
  level:
    com.achobeta: @logging.level@
    org.springframework: warn
    tech.powerjob.worker.background: warn
  config: classpath:logback-plus.xml