server:
  port: 9001

--- # 数据源配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/recruitment?serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

